# Form implementation generated from reading ui file '.\VScode\task_manager\MainWindowTaskManager.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.setEnabled(True)
        Frame.resize(934, 644)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".SF Soft Numeric")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        Frame.setFont(font)
        Frame.setMouseTracking(False)
        Frame.setAutoFillBackground(False)
        Frame.setStyleSheet(
            "QFrame{\n"
            "    border: 2px;\n"
            "    border-radius: 4px;\n"
            "    padding: 2px;\n"
            "    background-color: #1F2833;\n"
            "}"
        )
        Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetNoConstraint
        )
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_6.addItem(spacerItem)
        self.projectsBtn = QtWidgets.QPushButton(parent=Frame)
        self.projectsBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectsBtn.sizePolicy().hasHeightForWidth())
        self.projectsBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.projectsBtn.setFont(font)
        self.projectsBtn.setAutoFillBackground(False)
        self.projectsBtn.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(230, 230, 238);\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-radius: 6px;\n"
            "    border-color: #45A29E;\n"
            "    font: bold 14px;\n"
            "    min-width: 6em;\n"
            "    padding: 6px;\n"
            "    color: #45A29E;\n"
            "}"
        )
        self.projectsBtn.setAutoDefault(False)
        self.projectsBtn.setFlat(False)
        self.projectsBtn.setObjectName("projectsBtn")
        self.verticalLayout_6.addWidget(
            self.projectsBtn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter
        )
        self.taskManagerBtn = QtWidgets.QPushButton(parent=Frame)
        self.taskManagerBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.taskManagerBtn.sizePolicy().hasHeightForWidth()
        )
        self.taskManagerBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.taskManagerBtn.setFont(font)
        self.taskManagerBtn.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(230, 230, 238);\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-radius: 6px;\n"
            "    border-color: #45A29E;\n"
            "    font: bold 14px;\n"
            "    min-width: 6em;\n"
            "    padding: 6px;\n"
            "    color: #45A29E;\n"
            "}"
        )
        self.taskManagerBtn.setCheckable(False)
        self.taskManagerBtn.setAutoRepeat(False)
        self.taskManagerBtn.setAutoDefault(False)
        self.taskManagerBtn.setDefault(False)
        self.taskManagerBtn.setFlat(False)
        self.taskManagerBtn.setObjectName("taskManagerBtn")
        self.verticalLayout_6.addWidget(
            self.taskManagerBtn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter
        )
        self.profileBtn = QtWidgets.QPushButton(parent=Frame)
        self.profileBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileBtn.sizePolicy().hasHeightForWidth())
        self.profileBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.profileBtn.setFont(font)
        self.profileBtn.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(230, 230, 238);\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-radius: 6px;\n"
            "    border-color: #45A29E;\n"
            "    font: bold 14px;\n"
            "    min-width: 6em;\n"
            "    padding: 6px;\n"
            "    color: #45A29E;\n"
            "}"
        )
        self.profileBtn.setFlat(False)
        self.profileBtn.setObjectName("profileBtn")
        self.verticalLayout_6.addWidget(
            self.profileBtn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter
        )
        spacerItem1 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.project_name_title = QtWidgets.QLabel(parent=Frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.project_name_title.sizePolicy().hasHeightForWidth()
        )
        self.project_name_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.project_name_title.setFont(font)
        self.project_name_title.setMouseTracking(True)
        self.project_name_title.setAutoFillBackground(False)
        self.project_name_title.setStyleSheet(
            "QLabel {\n"
            "    background-color: #1F2834;\n"
            "    border-style: outset;\n"
            "    border-width: 1px;\n"
            "    border-radius: 8px;\n"
            "    border-color: #45A29E;\n"
            "    font: bold 18px;\n"
            "    min-width: 6em;\n"
            "    padding: 6px;\n"
            "  color: white;\n"
            "}"
        )
        self.project_name_title.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.project_name_title.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.project_name_title.setScaledContents(False)
        self.project_name_title.setWordWrap(False)
        self.project_name_title.setObjectName("project_name_title")
        self.verticalLayout_2.addWidget(self.project_name_title)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetNoConstraint
        )
        self.gridLayout.setObjectName("gridLayout")
        self.tasks_info = QtWidgets.QFrame(parent=Frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tasks_info.sizePolicy().hasHeightForWidth())
        self.tasks_info.setSizePolicy(sizePolicy)
        self.tasks_info.setStyleSheet(
            "QFrame{\n"
            "    border: 2px #6F6F6F;\n"
            "    border-radius: 10px;\n"
            "    padding: 2px;\n"
            "    background-color: #45A29E;\n"
            "}"
        )
        self.tasks_info.setObjectName("tasks_info")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tasks_info)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.all_tasks_numb = QtWidgets.QLabel(parent=self.tasks_info)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.all_tasks_numb.sizePolicy().hasHeightForWidth()
        )
        self.all_tasks_numb.setSizePolicy(sizePolicy)
        self.all_tasks_numb.setStyleSheet(
            "QLabel {\n"
            "    background-color: #D1D1D1;\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-radius: 8px;\n"
            "    border-color: #919191;\n"
            "    font: bold 14px;\n"
            "    min-width: 6em;\n"
            "    padding: 6px;\n"
            "    color: black;\n"
            "}\n"
            ""
        )
        self.all_tasks_numb.setObjectName("all_tasks_numb")
        self.horizontalLayout.addWidget(self.all_tasks_numb)
        self.labelAllTask = QtWidgets.QLabel(parent=self.tasks_info)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAllTask.sizePolicy().hasHeightForWidth())
        self.labelAllTask.setSizePolicy(sizePolicy)
        self.labelAllTask.setStyleSheet(
            "QLabel{\n"
            "    padding: 2px;\n"
            "    background-color: #45A29E;\n"
            "    border-style: outset;\n"
            "    border-width: 3px;\n"
            "    border-radius: 10px;\n"
            "    border-color: #1F2833;\n"
            "}\n"
            ""
        )
        self.labelAllTask.setObjectName("labelAllTask")
        self.horizontalLayout.addWidget(self.labelAllTask)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.done_tasks_numb = QtWidgets.QLabel(parent=self.tasks_info)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.done_tasks_numb.sizePolicy().hasHeightForWidth()
        )
        self.done_tasks_numb.setSizePolicy(sizePolicy)
        self.done_tasks_numb.setStyleSheet(
            "QLabel {\n"
            "    background-color: #D1D1D1;\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-radius: 8px;\n"
            "    border-color: #919191;\n"
            "    font: bold 14px;\n"
            "    min-width: 6em;\n"
            "    padding: 6px;\n"
            "    color: black;\n"
            "}\n"
            ""
        )
        self.done_tasks_numb.setObjectName("done_tasks_numb")
        self.horizontalLayout_2.addWidget(self.done_tasks_numb)
        self.labelDone = QtWidgets.QLabel(parent=self.tasks_info)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDone.sizePolicy().hasHeightForWidth())
        self.labelDone.setSizePolicy(sizePolicy)
        self.labelDone.setStyleSheet(
            "QLabel{\n"
            "    padding: 2px;\n"
            "    background-color: #45A29E;\n"
            "    border-style: outset;\n"
            "    border-width: 3px;\n"
            "    border-radius: 10px;\n"
            "    border-color: #1F2833;\n"
            "}\n"
            ""
        )
        self.labelDone.setObjectName("labelDone")
        self.horizontalLayout_2.addWidget(self.labelDone)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frozen_tasks_numb = QtWidgets.QLabel(parent=self.tasks_info)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frozen_tasks_numb.sizePolicy().hasHeightForWidth()
        )
        self.frozen_tasks_numb.setSizePolicy(sizePolicy)
        self.frozen_tasks_numb.setStyleSheet(
            "QLabel {\n"
            "    background-color: #D1D1D1;\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-radius: 8px;\n"
            "    border-color: #919191;\n"
            "    font: bold 14px;\n"
            "    min-width: 6em;\n"
            "    padding: 6px;\n"
            "    color: black;\n"
            "}\n"
            ""
        )
        self.frozen_tasks_numb.setObjectName("frozen_tasks_numb")
        self.horizontalLayout_4.addWidget(self.frozen_tasks_numb)
        self.labelFrozen = QtWidgets.QLabel(parent=self.tasks_info)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFrozen.sizePolicy().hasHeightForWidth())
        self.labelFrozen.setSizePolicy(sizePolicy)
        self.labelFrozen.setStyleSheet(
            "QLabel{\n"
            "    padding: 2px;\n"
            "    background-color: #45A29E;\n"
            "    border-style: outset;\n"
            "    border-width: 3px;\n"
            "    border-radius: 10px;\n"
            "    border-color: #1F2833;\n"
            "}\n"
            ""
        )
        self.labelFrozen.setObjectName("labelFrozen")
        self.horizontalLayout_4.addWidget(self.labelFrozen)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.gridLayout.addWidget(self.tasks_info, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=Frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(
            "QLabel{\n"
            "    padding: 2px;\n"
            "    background-color: #1F2833;\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-radius: 8px;\n"
            "    border-color: #45A29E;\n"
            "}"
        )
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.pushButtonAddTask = QtWidgets.QToolButton(parent=Frame)
        self.pushButtonAddTask.setStyleSheet(
            "QToolButton{\n"
            "    border-radius: 4px;\n"
            "    border-style: outset;\n"
            "    border-width: 3px;\n"
            "    border-radius: 8px;\n"
            "    border-color: #45A29E;\n"
            "    padding: 2px;\n"
            "    background-color: #1F2833;\n"
            "}\n"
            ""
        )
        self.pushButtonAddTask.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("D:/resourses.qrc/plus.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButtonAddTask.setIcon(icon)
        self.pushButtonAddTask.setObjectName("pushButtonAddTask")
        self.horizontalLayout_3.addWidget(self.pushButtonAddTask)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.label_5 = QtWidgets.QLabel(parent=Frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(
            "QLabel{\n"
            "    padding: 2px;\n"
            "    background-color: #1F2833;\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-radius: 8px;\n"
            "    border-color: #45A29E;\n"
            "}"
        )
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=Frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(
            "QLabel{\n"
            "    padding: 2px;\n"
            "    background-color: #1F2833;\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-radius: 8px;\n"
            "    border-color: #45A29E;\n"
            "}"
        )
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=Frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(
            "QLabel{\n"
            "    padding: 2px;\n"
            "    background-color: #1F2833;\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-radius: 8px;\n"
            "    border-color: #45A29E;\n"
            "}"
        )
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.to_do = QtWidgets.QVBoxLayout()
        self.to_do.setObjectName("to_do")
        self.scrollArea1 = QtWidgets.QScrollArea(parent=Frame)
        self.scrollArea1.setStyleSheet(
            "QScrollArea{\n"
            "    border-radius: 4px;\n"
            "    border-style: outset;\n"
            "    border-width: 3px;\n"
            "    border-radius: 8px;\n"
            "    border-color: white;\n"
            "    padding: 2px;\n"
            "    background-color: rgb(230, 230, 238);\n"
            "}"
        )
        self.scrollArea1.setWidgetResizable(True)
        self.scrollArea1.setObjectName("scrollArea1")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 183, 475))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayoutToDo = QtWidgets.QVBoxLayout()
        self.verticalLayoutToDo.setObjectName("verticalLayoutToDo")
        self.verticalLayout_3.addLayout(self.verticalLayoutToDo)
        self.scrollArea1.setWidget(self.scrollAreaWidgetContents)
        self.to_do.addWidget(self.scrollArea1)
        self.horizontalLayout_8.addLayout(self.to_do)
        self.in_progress = QtWidgets.QVBoxLayout()
        self.in_progress.setObjectName("in_progress")
        self.scrollArea2 = QtWidgets.QScrollArea(parent=Frame)
        self.scrollArea2.setStyleSheet(
            "QScrollArea{\n"
            "    border-radius: 4px;\n"
            "    border-style: outset;\n"
            "    border-width: 3px;\n"
            "    border-radius: 8px;\n"
            "    border-color: white;\n"
            "    padding: 2px;\n"
            "    background-color: rgb(230, 230, 238);\n"
            "}"
        )
        self.scrollArea2.setWidgetResizable(True)
        self.scrollArea2.setObjectName("scrollArea2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 182, 475))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayoutInProgress = QtWidgets.QVBoxLayout()
        self.verticalLayoutInProgress.setObjectName("verticalLayoutInProgress")
        self.verticalLayout_7.addLayout(self.verticalLayoutInProgress)
        self.scrollArea2.setWidget(self.scrollAreaWidgetContents_3)
        self.in_progress.addWidget(self.scrollArea2)
        self.horizontalLayout_8.addLayout(self.in_progress)
        self.closed = QtWidgets.QVBoxLayout()
        self.closed.setObjectName("closed")
        self.scrollArea3 = QtWidgets.QScrollArea(parent=Frame)
        self.scrollArea3.setStyleSheet(
            "QScrollArea{\n"
            "    border-radius: 4px;\n"
            "    border-style: outset;\n"
            "    border-width: 3px;\n"
            "    border-radius: 8px;\n"
            "    border-color: white;\n"
            "    padding: 2px;\n"
            "    background-color: rgb(230, 230, 238);\n"
            "}"
        )
        self.scrollArea3.setWidgetResizable(True)
        self.scrollArea3.setObjectName("scrollArea3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 183, 475))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayoutClosed = QtWidgets.QVBoxLayout()
        self.verticalLayoutClosed.setObjectName("verticalLayoutClosed")
        self.verticalLayout_9.addLayout(self.verticalLayoutClosed)
        self.scrollArea3.setWidget(self.scrollAreaWidgetContents_4)
        self.closed.addWidget(self.scrollArea3)
        self.horizontalLayout_8.addLayout(self.closed)
        self.frozen = QtWidgets.QVBoxLayout()
        self.frozen.setObjectName("frozen")
        self.scrollArea4 = QtWidgets.QScrollArea(parent=Frame)
        self.scrollArea4.setStyleSheet(
            "QScrollArea{\n"
            "    border-radius: 4px;\n"
            "    border-style: outset;\n"
            "    border-width: 3px;\n"
            "    border-radius: 8px;\n"
            "    border-color: white;\n"
            "    padding: 2px;\n"
            "    background-color: rgb(230, 230, 238);\n"
            "}"
        )
        self.scrollArea4.setWidgetResizable(True)
        self.scrollArea4.setObjectName("scrollArea4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 182, 475))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayoutFrozen = QtWidgets.QVBoxLayout()
        self.verticalLayoutFrozen.setObjectName("verticalLayoutFrozen")
        self.verticalLayout_11.addLayout(self.verticalLayoutFrozen)
        self.scrollArea4.setWidget(self.scrollAreaWidgetContents_5)
        self.frozen.addWidget(self.scrollArea4)
        self.horizontalLayout_8.addLayout(self.frozen)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.projectsBtn.setText(_translate("Frame", "Projects"))
        self.taskManagerBtn.setText(_translate("Frame", "Task Manager"))
        self.profileBtn.setText(_translate("Frame", "Profile"))
        self.project_name_title.setText(
            _translate(
                "Frame",
                '<html><head/><body><p><span style=" color:#5affef;">Project name</span></p></body></html>',
            )
        )
        self.all_tasks_numb.setText(_translate("Frame", "All tasks:"))
        self.labelAllTask.setText(
            _translate(
                "Frame",
                '<html><head/><body><p><span style=" font-size:16pt;">num</span></p></body></html>',
            )
        )
        self.done_tasks_numb.setText(_translate("Frame", "Done:"))
        self.labelDone.setText(
            _translate(
                "Frame",
                '<html><head/><body><p><span style=" font-size:16pt;">num</span></p></body></html>',
            )
        )
        self.frozen_tasks_numb.setText(_translate("Frame", "Frozen:"))
        self.labelFrozen.setText(
            _translate(
                "Frame",
                '<html><head/><body><p><span style=" font-size:16pt;">num</span></p></body></html>',
            )
        )
        self.label_4.setText(
            _translate(
                "Frame",
                '<html><head/><body><p><span style=" color:#00ffec;">To do</span></p></body></html>',
            )
        )
        self.label_5.setText(
            _translate(
                "Frame",
                '<html><head/><body><p><span style=" color:#00ffed;">In progress</span></p></body></html>',
            )
        )
        self.label_6.setText(
            _translate(
                "Frame",
                '<html><head/><body><p><span style=" color:#00ffec;">Closed</span></p></body></html>',
            )
        )
        self.label_7.setText(
            _translate(
                "Frame",
                '<html><head/><body><p><span style=" color:#00ffec;">Frozen</span></p></body></html>',
            )
        )
