# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(264, 130)
        Frame.setMaximumSize(QtCore.QSize(264, 130))
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcum_label_auth = QtWidgets.QLabel(parent=Frame)
        self.welcum_label_auth.setMinimumSize(QtCore.QSize(246, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.welcum_label_auth.setFont(font)
        self.welcum_label_auth.setObjectName("welcum_label_auth")
        self.verticalLayout.addWidget(self.welcum_label_auth)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.usr_label_auth = QtWidgets.QLabel(parent=Frame)
        self.usr_label_auth.setObjectName("usr_label_auth")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.usr_label_auth)
        self.usr_text_auth = QtWidgets.QLineEdit(parent=Frame)
        self.usr_text_auth.setObjectName("usr_text_auth")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.usr_text_auth)
        self.password_label_auth = QtWidgets.QLabel(parent=Frame)
        self.password_label_auth.setObjectName("password_label_auth")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.password_label_auth)
        self.password_text_auth = QtWidgets.QLineEdit(parent=Frame)
        self.password_text_auth.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_text_auth.setObjectName("password_text_auth")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.password_text_auth)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.login_button_auth = QtWidgets.QPushButton(parent=Frame)
        self.login_button_auth.setObjectName("login_button_auth")
        self.horizontalLayout.addWidget(self.login_button_auth)
        self.cancel_button_auth = QtWidgets.QPushButton(parent=Frame)
        self.cancel_button_auth.setObjectName("cancel_button_auth")
        self.horizontalLayout.addWidget(self.cancel_button_auth)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.welcum_label_auth.setText(_translate("Frame", "Welcome to Application"))
        self.usr_label_auth.setText(_translate("Frame", "UserName:"))
        self.password_label_auth.setText(_translate("Frame", "Password:"))
        self.login_button_auth.setText(_translate("Frame", "Login"))
        self.cancel_button_auth.setText(_translate("Frame", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec())
