# Form implementation generated from reading ui file 'registr.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(494, 323)
        self.layoutWidget = QtWidgets.QWidget(parent=Frame)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 150, 285, 167))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wecum_label_reg = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wecum_label_reg.setFont(font)
        self.wecum_label_reg.setObjectName("wecum_label_reg")
        self.verticalLayout.addWidget(self.wecum_label_reg)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.usr_label_reg = QtWidgets.QLabel(parent=self.layoutWidget)
        self.usr_label_reg.setObjectName("usr_label_reg")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.usr_label_reg)
        self.usr_name_text_reg = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.usr_name_text_reg.setStyleSheet("border-radius: 8px;\n"
"")
        self.usr_name_text_reg.setObjectName("usr_name_text_reg")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.usr_name_text_reg)
        self.email_label_reg = QtWidgets.QLabel(parent=self.layoutWidget)
        self.email_label_reg.setObjectName("email_label_reg")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.email_label_reg)
        self.email_text_reg = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.email_text_reg.setStyleSheet("border-radius: 8px;")
        self.email_text_reg.setObjectName("email_text_reg")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.email_text_reg)
        self.password_label_reg = QtWidgets.QLabel(parent=self.layoutWidget)
        self.password_label_reg.setObjectName("password_label_reg")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.password_label_reg)
        self.password_text_reg = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.password_text_reg.setStyleSheet("border-radius: 8px;")
        self.password_text_reg.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_text_reg.setObjectName("password_text_reg")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.password_text_reg)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.confirm_button_reg = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.confirm_button_reg.setObjectName("confirm_button_reg")
        self.horizontalLayout.addWidget(self.confirm_button_reg)
        self.cancel_button_reg = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.cancel_button_reg.setAutoDefault(False)
        self.cancel_button_reg.setDefault(False)
        self.cancel_button_reg.setFlat(False)
        self.cancel_button_reg.setObjectName("cancel_button_reg")
        self.horizontalLayout.addWidget(self.cancel_button_reg)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.GIF = QtWidgets.QLabel(parent=Frame)
        self.GIF.setGeometry(QtCore.QRect(110, -40, 281, 191))
        self.GIF.setText("")
        self.GIF.setObjectName("GIF")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.wecum_label_reg.setText(_translate("Frame", "Welcome to Registration"))
        self.usr_label_reg.setText(_translate("Frame", "UserName:"))
        self.email_label_reg.setText(_translate("Frame", "Email:"))
        self.password_label_reg.setText(_translate("Frame", "Password:"))
        self.confirm_button_reg.setText(_translate("Frame", "Confirm"))
        self.cancel_button_reg.setText(_translate("Frame", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec())
